### ISSUE TITLE
Use ESLint API to get rules

### ISSUE THREAD

**Issue by IanVS** [sun1x/eslint-to-editorconfig#2]
Hi, this looks very useful.

Have you considered using [`getConfigForFiles()`](http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile) instead of pulling the rule configuration straight from an `.eslintrc`?  This would have the benefit of detecting rules extended from a sharable config like [standard](https://github.com/feross/eslint-config-standard).

**Comment by snanovskyi** [comment]
@IanVS Hi. I released new version powered by ESLint CLIEngine.
Hope you like it:)
