### ISSUE TITLE
airbnb config

### ISSUE THREAD

**Issue by maitriyogin** [sun1x/eslint-to-editorconfig#3]
Hi,
I'v tried running this against airbnb's config and got the following error:
/usr/local/lib/node_modules/eslint-to-editorconfig/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: /usr/local/lib/node_modules/eslint-config-airbnb/rules/best-practices.js:
    Configuration for rule "no-labels" is invalid:
    Value "2,[object Object]" has more items than allowed.

Any ideas?
/Stephen.

**Comment by quasipedia** [comment]
Same problem here. :disappointed:

**Comment by matthewadams** [comment]
Same here except using `standard` (see https://standardjs.com)

**Comment by matthewadams** [comment]
Looks like this is related to https://github.com/feross/eslint-config-standard/issues/23

**Comment by snanovskyi** [comment]
@maitriyogin @quasipedia @matthewadams sorry for not responding. Was busy at work and university. And a bit lazy :)
It caused by ESLint update to 2.0 where some rules were changed/removed. I will fix it on weekend.

**Comment by matthewadams** [comment]
That'd be sweet, my man.  Thanks.

**Comment by snanovskyi** [comment]
@matthewadams @quasipedia @maitriyogin I updated the package. Install it locally(or globally) against all your configs.
It loads dependencies from node_modules where it installed. So if you use Airbnb's config, install it in the same directory.
